# Generated by Django 4.2.6 on 2023-11-01 12:56

from django.db import migrations, models
import django.db.models.deletion
from collections import namedtuple


PY, JS = 'Python', 'JavaScript'
LANGUAGES = (PY, JS)
FRAMEWORKS = {
    PY: ('Django', 'Django REST Framework', 'Flask', 'Fast API'),
    JS: ('React', 'Node.js', 'Vue.js', 'AngularJS'),
}
OptionDataHolder = namedtuple(
    'OptionDataHolder',
    'name option_type language framework'
)
OPTIONS = (
    OptionDataHolder('Pandas', 'LIB', PY, None),
    OptionDataHolder('NumPy', 'LIB', PY, None),
)


def forwards_func(apps, schema_editor):
    ProgrammingLanguage = apps.get_model("core", "ProgrammingLanguage")
    Framework = apps.get_model("core", "Framework")
    Option = apps.get_model("core", "Option")

    db_alias = schema_editor.connection.alias
    ProgrammingLanguage.objects.using(db_alias).bulk_create([
        ProgrammingLanguage(name=name) for name in LANGUAGES
    ])
    language_name_record_mapping = {
        rec.name: rec
        for rec in ProgrammingLanguage.objects.all()
    }
    for l_name, frameworks in FRAMEWORKS.items():
        Framework.objects.using(db_alias).bulk_create([
            Framework(
                name=name,
                language=language_name_record_mapping.get(l_name)
            )
            for name in frameworks
        ])
    Option.objects.using(db_alias).bulk_create([
        Option(
            name=option_data.name,
            option_type=option_data.option_type,
            language=language_name_record_mapping.get(option_data.language),
            framework=None
        )
        for option_data in OPTIONS
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('option_type', models.CharField(choices=[('FRAME', 'Framework'), ('LIB', 'Library'), ('PACK', 'Package'), ('D_P', 'Design Pattern')], max_length=5)),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.framework')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programminglanguage')),
            ],
        ),
        migrations.AddField(
            model_name='framework',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programminglanguage'),
        ),
        migrations.RunPython(forwards_func),
    ]
